name: Deploy to OSS

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
       # with:
       #   submodules: true

      # 部署前删掉一些无用文件以节省流量
      - name: Delete git
        run: |
          rm -rf .git
          rm -rf .github

      # 部署到阿里云 OSS
      - name: Deploy to OSS
        uses: saltbo/uptoc@master
        with:
          driver: oss
          region: cn-shanghai
          bucket: eallion-nav
          dist: ./
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.ACCESS_KEY_ID }}
          UPTOC_UPLOADER_SK: ${{ secrets.ACCESS_KEY_SECRET }}